### PR TITLE
Force SSL on Wilfred

### PR DESCRIPTION
**Pull request by leighmcculloch**
### What
Force SSL on Wilfred

### Why
Heroku domains support SSL, there's no reason not to.

### CODE REVIEW

**Comment by benwalsh** [comment]
lgtm

**Comment by thatha** [comment]
This breaks OAuth with Github--not sure why, I just know that if you go to https://wilfredapp.herokuapp.com/ you can't login.

**Comment by leighmcculloch** [comment]
thanks i'll address that before i merge

**Comment by leighmcculloch** [comment]
if i can

**Pull request closed without merging**
